### ISSUE TITLE
Quotations Issue

### ISSUE THREAD

**Issue by subha-v** [linguisticsjusticeleague/newStorybookImages#8]
In any book with quotations, the program breaks as it tries to parse the quotations. Perhaps we can implement something to change the quotation symbol to something else when passing through the api, and then change it back to quotations when displaying them. 

![image](https://user-images.githubusercontent.com/71041442/180656881-0906294d-1fce-49a8-a8e9-a10a4ae4b83a.png)

**Comment by Eshaancoding** [comment]
With @madhuriaddepalli suggestion of changing the `removeChar` function to

```py
def removeChar(text): 
    special_char_dict = {
        "’": "'",
        "”": "'",
        "“": "'",
        "—": "-",
        "\"": ""
    }
    for key in special_char_dict:
        text = text.replace(key, special_char_dict[key])

    return text 
```

We were able to remove the quotation issue by simply removing the quotation marks from the text.
