### ISSUE TITLE
Two images per page issue

### ISSUE THREAD

**Issue by subha-v** [linguisticsjusticeleague/newStorybookImages#9]
When there are two images per page, oftentimes issues arise when the final translations are rendered on the page - see screenshots for example:

![image](https://user-images.githubusercontent.com/71041442/181397453-43236f63-d329-408c-a714-bd70d09d2cdd.png)
![image](https://user-images.githubusercontent.com/71041442/181397469-4079b5a5-9725-4d84-8715-0960bbadff2f.png)

I have uploaded some books that have two images per page so people can test/resolve this.
[Friends_fu
[Animals_get_legs.pdf](https://github.com/linguisticsjusticeleague/newStorybookImages/files/9204436/Animals_get_legs.pdf)
n_day.pdf](https://github.com/linguisticsjusticeleague/newStorybookImages/files/9204435/Friends_fun_day.pdf)

**Comment by Eshaancoding** [comment]
Fixed with better text detection: [2065acf](https://github.com/linguisticsjusticeleague/newStorybookImages/commit/2065acf524339f163ba01017663e2e7e50905c03)

[Output.pdf](https://github.com/linguisticsjusticeleague/newStorybookImages/files/9271024/Output.pdf)

**Comment by subji6** [comment]
nice
